# Unbind F and G
F ignore
G ignore

space cycle pause

A seek -1 exact
a seek -5 exact
d no-osd sub-seek 0; 
s no-osd sub-seek -1
f no-osd sub-seek 1
g seek 5 exact
G seek 1 exact

# Rebind subtitle font size to whatever you want
Meta+k add sub-scale +0.1
Meta+j add sub-scale -0.1
Meta+r set sub-scale 1    # reset subtitle size to default

ctrl+v script-binding update-anki-card
ctrl+t script-binding toggle-clipboard-insertion
ctrl+d script-binding toggle-debug-mode

Meta+v script-binding update-anki-card
Meta+t script-binding toggle-clipboard-insertion
Meta+d script-binding toggle-debug-mode

tab  script-binding uosc/toggle-ui

screen=1
