save-position-on-quit=yes


# Spaces don't have to be escaped.
osd-playing-msg=File:${filename}

# SCREENSHOT
screenshot-png-compression=0
screenshot-high-bit-depth=yes  # Optional: Better quality
screenshot-template="%F_%P"


audio-file-auto=fuzzy  
audio-pitch-correction=yes  
audio-samplerate=192000

# OSD
osd-level=0
osd-bar=no
osc=no

# Fullscreen (experimental)
border=no
window-maximized=yes
window-dragging=no
geometry=100%x100%+0+0
macos-geometry-calculation=visible # visible/whole
autofit-larger=100%x100%
native-fs=yes

# Fullscreen (old)
# border=no
# window-maximized=yes
# window-dragging=no
# geometry=100%x100%+0+0
# macos-geometry-calculation=visible # visible/whole
# autofit-larger=100%x100%

# SUBS
sub-font-size=40
sub-font='Hiragino mincho pro w3' ##'BIZ UDPMincho'
sub-outline-size=0
## --sub-border-style=<outline-and-shadow|opaque-box|background-box>
sub-border-style=background-box
sub-color=1/1/1/1
sub-back-color=0/0/0/0.825
sub-delay=0
